
FROM alpine:3.12.3

LABEL maintainer="eirture@gmail.com"

ARG VERSION="0.0.1"

ADD https://bizseer-public.bizseer.com/release/walle/${VERSION}/walle /usr/local/bin/walle

RUN chmod a+x /usr/local/bin/walle
